<?php

declare(strict_types=1);

/**
 * Database Backup Endpoint
 *
 * GET    /backup               -> List all available backup files
 * GET    /backup/{filename}    -> Download a specific backup file
 * POST   /backup               -> Create a new data-only backup (5-file retention)
 * PUT    /backup/{filename}    -> Restore the database from a backup file
 *
 * -----------------------------------------------------------------------------
 * Timezone policy
 * -----------------------------------------------------------------------------
 * Filenames and the GET listing MUST agree on a single wall clock. The filename
 * is stamped by MySQL via DATE_FORMAT(NOW(), …) in the session timezone, so the
 * listing must be formatted the same way — not via PHP's date(), which reads an
 * entirely independent php.ini timezone.
 *
 * Previously the listing used date('Y-m-d H:i:s', filemtime($file)). When
 * php.ini was on UTC and MySQL was on Asia/Manila, that produced an 8-hour skew
 * against the filename. The rules now are:
 *
 *   1. MySQL is the source of truth for "now" — see dbTimezone().
 *   2. The listing prefers the timestamp baked into the filename (it was
 *      generated by NOW(), so it *is* the DB clock).
 *   3. Any fallback path formats filemtime() explicitly in the DB timezone.
 *
 * Nothing here relies on PHP's global date.timezone matching MySQL's.
 *
 * -----------------------------------------------------------------------------
 * Security note
 * -----------------------------------------------------------------------------
 * The backups/ directory MUST NOT be reachable as a static directory through
 * the web server. If Apache/nginx serves files from here directly, anyone can
 * download a full dump without hitting this endpoint or authenticating.
 * Add a deny-all rule for /backups/ in the vhost config.
 */

define('ITS_ME_JUSTTOVERIFY', true);

require_once 'checkuser.php';
require_once 'logger.php';

const BACKUP_LIMIT       = 5;
const BACKUP_FILE_REGEX  = '/^[A-Za-z0-9._-]+\.sql$/';
const BACKUP_NAME_PREFIX = 'memoria_db_';

$userData = checkuser();

if (($userData['role'] ?? null) !== ROLE_ADMIN) {
    Response::error('Forbidden. Insufficient privileges.', 403);
}

// -----------------------------------------------------------------------------
// 0. Best-effort sync of PHP's clock with the DB session timezone
// -----------------------------------------------------------------------------
// Convenience only — a fallback for any stray date()/time() callers we don't
// control. It is NOT the source of truth: every timestamp produced below is
// formatted explicitly via dbTimezone().
//
// Quirks handled here:
//   * PHP's date_default_timezone_set() accepts only IANA names. It rejects
//     fixed offsets like '+08:00' even though DateTimeZone accepts them.
//     Offsets are therefore converted to a canonical IANA name first.
//   * 'SYSTEM' is a valid MySQL value but NOT a valid PHP timezone.
//   * If conversion fails, we silently skip — every code path here already
//     formats in the DB zone explicitly, so the global default is cosmetic.
if (defined('DB_TIMEZONE') && DB_TIMEZONE !== '' && strtoupper((string) DB_TIMEZONE) !== 'SYSTEM') {
    $tzValue = (string) DB_TIMEZONE;

    // Normalise a fixed offset ('+08:00', '-05:30') to a real IANA name.
    if (preg_match('/^([+-])(\d{2}):(\d{2})$/', $tzValue, $m)) {
        $offsetSeconds = ((int) $m[2] * 3600 + (int) $m[3] * 60) * ($m[1] === '-' ? -1 : 1);
        $name = timezone_name_from_abbr('', $offsetSeconds, 0);
        $tzValue = ($name !== false) ? $name : null;
    }

    if ($tzValue !== null && !@date_default_timezone_set($tzValue)) {
        error_log('backup.php: DB_TIMEZONE "' . DB_TIMEZONE . '" is not a valid PHP timezone.');
    }
}

@set_time_limit(0);

// -----------------------------------------------------------------------------
// 1. Setup backup directory
// -----------------------------------------------------------------------------
$backupDir = __DIR__ . '/backups/';

if (!is_dir($backupDir) && !mkdir($backupDir, 0755, true) && !is_dir($backupDir)) {
    Response::error('Unable to create the backup directory.', 500);
}

// Normalised, trailing-slash path used for all containment checks.
$backupDir = rtrim((string) realpath($backupDir), DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR;

// -----------------------------------------------------------------------------
// 2. Helpers
// -----------------------------------------------------------------------------

/**
 * Resolve MySQL's session timezone into a PHP DateTimeZone.
 *
 * Handles all three forms @@session.time_zone can take:
 *   - A named zone   ('Asia/Manila')   -> used directly
 *   - A fixed offset ('+08:00')        -> used directly
 *   - 'SYSTEM'       (or anything odd) -> derived from NOW() vs UTC_TIMESTAMP()
 *
 * Falls back to UTC if MySQL can't be queried at all.
 */
function dbTimezone(PDO $pdo): DateTimeZone
{
    static $tz = null;
    if ($tz instanceof DateTimeZone) {
        return $tz;
    }

    // Preferred path: the raw session value, if PHP can parse it directly.
    try {
        $sessionTz = (string) $pdo->query('SELECT @@session.time_zone')->fetchColumn();

        if ($sessionTz !== '' && strtoupper($sessionTz) !== 'SYSTEM') {
            return $tz = new DateTimeZone($sessionTz);
        }
    } catch (Throwable $e) {
        // fall through to offset derivation
    }

    // Fallback: derive the numeric offset from the DB clock itself.
    // NOW() is session-tz; UTC_TIMESTAMP() is UTC; TIMEDIFF() is the offset.
    try {
        $diff = (string) $pdo->query('SELECT TIMEDIFF(NOW(), UTC_TIMESTAMP())')->fetchColumn();

        // MySQL returns e.g. "08:00:00" or "-05:30:00".
        if (preg_match('/^(-?)(\d{1,2}):(\d{2})/', $diff, $m)) {
            $sign   = $m[1] === '-' ? '-' : '+';
            $hour   = str_pad($m[2], 2, '0', STR_PAD_LEFT);
            $minute = $m[3];
            return $tz = new DateTimeZone($sign . $hour . ':' . $minute);
        }
    } catch (Throwable $e) {
        // fall through to UTC
    }

    return $tz = new DateTimeZone('UTC');
}

/**
 * Pull the timestamp baked into a backup filename by MySQL's NOW().
 *
 * Returns "YYYY-MM-DD HH:MM:SS", or null if the name doesn't match our scheme.
 * The filename is the authoritative record of when the snapshot was taken,
 * because it was produced by the database — not by PHP.
 */
function parseBackupTimestamp(string $filename): ?string
{
    $pattern = '/^' . preg_quote(BACKUP_NAME_PREFIX, '/')
        . '(\d{4}-\d{2}-\d{2})_(\d{2})-(\d{2})-(\d{2})\.sql$/';

    if (!preg_match($pattern, $filename, $m)) {
        return null;
    }

    return "{$m[1]} {$m[2]}:{$m[3]}:{$m[4]}";
}

/**
 * Resolve a user supplied name to a real file inside the backup directory.
 * Returns null when the name is invalid, missing, or escapes the directory.
 */
function resolveBackupPath(string $name, string $backupDir): ?string
{
    $name = basename(trim($name));

    if ($name === '' || !preg_match(BACKUP_FILE_REGEX, $name)) {
        return null;
    }

    $real = realpath($backupDir . $name);

    if ($real === false || !is_file($real)) {
        return null;
    }

    // Final safety net against directory traversal / symlink escapes.
    if (strncmp($real, $backupDir, strlen($backupDir)) !== 0) {
        return null;
    }

    return $real;
}

/**
 * Render a PHP value as a safe SQL literal.
 */
function sqlLiteral(PDO $pdo, mixed $value): string
{
    if ($value === null) {
        return 'NULL';
    }
    if (is_bool($value)) {
        return $value ? '1' : '0';
    }
    if (is_int($value) || is_float($value)) {
        return (string) $value;
    }

    return $pdo->quote((string) $value);
}

/**
 * Quote an identifier (table / column name) for MySQL.
 */
function sqlIdentifier(string $identifier): string
{
    return '`' . str_replace('`', '``', $identifier) . '`';
}

/**
 * Stream a data-only dump of every table to disk.
 *
 * Generated (shadow) columns are intentionally skipped — MySQL refuses
 * explicit values for them and recomputes them from `deleted_at`.
 */
function createBackup(PDO $pdo, string $backupDir): string
{
    $tables = $pdo->query('SHOW TABLES')->fetchAll(PDO::FETCH_COLUMN) ?: [];

    // Filename uses MySQL's own clock, not PHP's. Because the session timezone
    // is pinned via PDO::MYSQL_ATTR_INIT_COMMAND, NOW() reflects the DB wall
    // clock — the same clock every created_at / transfer_date in the dump uses.
    $stamp     = (string) $pdo->query('SELECT DATE_FORMAT(NOW(), "%Y-%m-%d_%H-%i-%s")')->fetchColumn();
    $filename  = BACKUP_NAME_PREFIX . $stamp . '.sql';
    $tmpPath   = $backupDir . $filename . '.tmp';
    $finalPath = $backupDir . $filename;

    $handle = fopen($tmpPath, 'wb');
    if ($handle === false) {
        throw new RuntimeException('Unable to open the backup file for writing.');
    }

    // Prepared lookup for generated columns, per table.
    $genStmt = $pdo->prepare(
        "SELECT COLUMN_NAME
           FROM information_schema.COLUMNS
          WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME   = :table
            AND EXTRA LIKE '%GENERATED%'"
    );

    try {
        // Capture the live session timezone and bake it into the dump so the
        // restore runs in the same zone. @@session.time_zone returns either a
        // name ('Asia/Manila'), an offset ('+08:00'), or the literal 'SYSTEM';
        // all three are valid inputs to SET time_zone.
        //
        // Why it matters: the log_grave_transfer trigger uses NOW() for
        // transfer_date. Without a SET time_zone in the dump, a restore runs in
        // whatever timezone the restoring connection happens to have, silently
        // shifting any transfer_log rows the trigger writes during the restore.
        $sessionTz = (string) $pdo->query('SELECT @@session.time_zone')->fetchColumn();

        // Header timestamp is formatted explicitly in the DB timezone — never
        // via PHP's date(), which reads an unrelated php.ini setting.
        $headerTime = (new DateTimeImmutable('now', dbTimezone($pdo)))->format('Y-m-d H:i:s');

        fwrite($handle, "-- Data-only backup generated {$headerTime} (timezone: {$sessionTz})\n");
        fwrite($handle, "SET FOREIGN_KEY_CHECKS=0;\n");
        fwrite($handle, "SET NAMES utf8mb4;\n");
        fwrite($handle, "SET time_zone = " . $pdo->quote($sessionTz) . ";\n\n");

        foreach ($tables as $table) {
            $quotedTable = sqlIdentifier((string) $table);

            // Which columns must we skip for this table?
            $genStmt->execute([':table' => $table]);
            $generated = $genStmt->fetchAll(PDO::FETCH_COLUMN) ?: [];
            $skip      = array_flip($generated); // fast isset() lookup

            fwrite($handle, "TRUNCATE TABLE {$quotedTable};\n");

            $stmt = $pdo->query("SELECT * FROM {$quotedTable}");

            while (($row = $stmt->fetch(PDO::FETCH_ASSOC)) !== false) {
                // Drop generated columns from this row before writing it.
                $row = array_filter(
                    $row,
                    static fn(string $col): bool => !isset($skip[$col]),
                    ARRAY_FILTER_USE_KEY
                );

                if ($row === []) {
                    continue; // row was nothing but generated columns
                }

                $columns = implode(', ', array_map(
                    static fn(string $c): string => sqlIdentifier($c),
                    array_keys($row)
                ));

                $values = implode(', ', array_map(
                    static fn(mixed $v): string => sqlLiteral($pdo, $v),
                    array_values($row)
                ));

                fwrite($handle, "INSERT INTO {$quotedTable} ({$columns}) VALUES ({$values});\n");
            }

            fwrite($handle, "\n");
        }

        fwrite($handle, "SET FOREIGN_KEY_CHECKS=1;\n");
    } finally {
        fclose($handle);
    }

    if (!rename($tmpPath, $finalPath)) {
        @unlink($tmpPath);
        throw new RuntimeException('Unable to finalise the backup file.');
    }

    return $filename;
}

/**
 * Delete the oldest backups so that only BACKUP_LIMIT files remain.
 */
function pruneBackups(string $backupDir): array
{
    $files = glob($backupDir . '*.sql') ?: [];

    usort($files, static fn(string $a, string $b): int => filemtime($b) <=> filemtime($a));

    $deleted = [];

    foreach (array_slice($files, BACKUP_LIMIT) as $file) {
        if (is_file($file) && @unlink($file)) {
            $deleted[] = basename($file);
        }
    }

    return $deleted;
}

/**
 * Split a SQL dump into individual statements.
 *
 * Quote- and comment-aware, so semicolons inside string literals are safe.
 */
function splitSqlStatements(string $sql): array
{
    $statements = [];
    $buffer     = '';
    $length     = strlen($sql);

    $inSingle = $inDouble = $inBacktick = false;
    $inLineComment = $inBlockComment = false;

    for ($i = 0; $i < $length; $i++) {
        $char = $sql[$i];
        $next = $sql[$i + 1] ?? '';

        // --- Comments -------------------------------------------------------
        if ($inLineComment) {
            if ($char === "\n") {
                $inLineComment = false;
                $buffer .= $char;
            }
            continue;
        }

        if ($inBlockComment) {
            if ($char === '*' && $next === '/') {
                $inBlockComment = false;
                $i++;
            }
            continue;
        }

        // --- Inside a quoted literal ----------------------------------------
        if ($inSingle || $inDouble || $inBacktick) {
            $buffer .= $char;

            if ($char === '\\' && !$inBacktick && $next !== '') {
                $buffer .= $next;
                $i++;
                continue;
            }

            $closing = $inSingle ? "'" : ($inDouble ? '"' : '`');

            if ($char === $closing) {
                if ($next === $closing) {   // doubled quote = escaped quote
                    $buffer .= $next;
                    $i++;
                    continue;
                }
                $inSingle = $inDouble = $inBacktick = false;
            }
            continue;
        }

        // --- Outside any literal --------------------------------------------
        if ($char === '-' && $next === '-') {
            $after = $sql[$i + 2] ?? ' ';
            if ($after === ' ' || $after === "\t" || $after === "\n") {
                $inLineComment = true;
                $i++;
                continue;
            }
        }

        if ($char === '#') {
            $inLineComment = true;
            continue;
        }

        if ($char === '/' && $next === '*') {
            $inBlockComment = true;
            $i++;
            continue;
        }

        if ($char === "'") {
            $inSingle  = true;
            $buffer .= $char;
            continue;
        }
        if ($char === '"') {
            $inDouble  = true;
            $buffer .= $char;
            continue;
        }
        if ($char === '`') {
            $inBacktick = true;
            $buffer .= $char;
            continue;
        }

        if ($char === ';') {
            $statement = trim($buffer);
            if ($statement !== '') {
                $statements[] = $statement;
            }
            $buffer = '';
            continue;
        }

        $buffer .= $char;
    }

    $statement = trim($buffer);
    if ($statement !== '') {
        $statements[] = $statement;
    }

    return $statements;
}

/**
 * Restore the database from a dump file. Returns the number of statements run.
 */
function restoreBackup(PDO $pdo, string $filePath): int
{
    $sql = file_get_contents($filePath);

    if ($sql === false || trim($sql) === '') {
        throw new RuntimeException('The backup file is empty or unreadable.');
    }

    $statements = splitSqlStatements($sql);
    $executed   = 0;

    foreach ($statements as $index => $statement) {
        try {
            $pdo->exec($statement);
            $executed++;
        } catch (PDOException $e) {
            throw new RuntimeException(
                sprintf('Restore aborted at statement #%d: %s', $index + 1, $e->getMessage()),
                0,
                $e
            );
        }
    }

    return $executed;
}

// -----------------------------------------------------------------------------
// 3. Routing
// -----------------------------------------------------------------------------
$method = $_SERVER['REQUEST_METHOD'] ?? '';

// Path: /backup/{filename}  (also accepts ?file= as a fallback)
$pathInfo  = $_GET['path_info'] ?? $_SERVER['PATH_INFO'] ?? '';
$pathParts = array_values(array_filter(explode('/', trim((string) $pathInfo, '/'))));

$resourceId = $pathParts[0] ?? ($_GET['file'] ?? null);
$resourceId = is_string($resourceId) ? trim($resourceId) : null;

// -----------------------------------------------------------------------------
// 4. GET — download a single file, or list everything
// -----------------------------------------------------------------------------
if ($method === 'GET') {

    // 4a. Download a specific backup
    if ($resourceId !== null && $resourceId !== '') {
        $filePath = resolveBackupPath($resourceId, $backupDir);

        if ($filePath === null) {
            Response::error('Backup file not found.', 404);
        }

        // Discard anything already buffered so the stream stays clean.
        while (ob_get_level() > 0) {
            ob_end_clean();
        }

        $downloadName = basename($filePath);

        header('Content-Type: application/sql; charset=utf-8');
        header('Content-Disposition: attachment; filename="' . $downloadName . '"');
        header('Content-Length: ' . filesize($filePath));
        header('Content-Transfer-Encoding: binary');
        header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
        header('Pragma: no-cache');
        header('X-Content-Type-Options: nosniff');

        readfile($filePath);
        exit;
    }

    // 4b. List available backups (newest first)
    //
    // The `date` field MUST agree with the timestamp encoded in the filename
    // (which MySQL produced from NOW() in the session timezone).
    //
    // Strategy:
    //   * Prefer parsing the timestamp straight out of the filename — it is
    //     the authoritative record of when the snapshot was taken, and it
    //     needs no DB round-trip.
    //   * Fall back to formatting filemtime() explicitly in the DB timezone
    //     for any file that doesn't follow our naming convention.
    //
    // Either path avoids PHP's date() / date.timezone entirely.
    $files = glob($backupDir . '*.sql') ?: [];

    // Sort by mtime once, up front. mtime is a UTC epoch value, so ordering
    // is unambiguous and independent of whatever timezone we format in below.
    usort($files, static fn(string $a, string $b): int => filemtime($b) <=> filemtime($a));

    $tz      = dbTimezone($pdo);
    $backups = [];

    foreach ($files as $file) {
        $name = basename($file);

        $date = parseBackupTimestamp($name);

        if ($date === null) {
            $mtime = filemtime($file);
            $date  = $mtime !== false
                ? (new DateTimeImmutable('@' . $mtime))->setTimezone($tz)->format('Y-m-d H:i:s')
                : 'unknown';
        }

        $backups[] = [
            'filename'      => $name,
            'size_in_bytes' => filesize($file),
            'date'          => $date,
            'download'      => '/api/backup/' . rawurlencode($name),
        ];
    }

    Response::success('Backups retrieved successfully.', $backups);
}

// -----------------------------------------------------------------------------
// 5. POST — create a new backup and enforce the retention limit
// -----------------------------------------------------------------------------
if ($method === 'POST') {
    try {
        $filename = createBackup($pdo, $backupDir);
        $deleted  = pruneBackups($backupDir);

        Response::success('Snapshot created successfully: ' . $filename, [
            'filename'      => $filename,
            'size_in_bytes' => filesize($backupDir . $filename),
            'pruned'        => $deleted,
        ]);
    } catch (Throwable $e) {
        Response::error('Backup failed: ' . $e->getMessage(), 500);
    }
}

// -----------------------------------------------------------------------------
// 6. PUT — restore the database from a backup file
// -----------------------------------------------------------------------------
if ($method === 'PUT') {
    if ($resourceId === null || $resourceId === '') {
        Response::error('Filename is required to restore a backup.', 400);
    }

    $filePath = resolveBackupPath($resourceId, $backupDir);

    if ($filePath === null) {
        Response::error('Backup file not found.', 404);
    }

    try {
        $executed = restoreBackup($pdo, $filePath);

        Response::success('Database restored successfully: ' . basename($filePath), [
            'filename'   => basename($filePath),
            'statements' => $executed,
        ]);
    } catch (Throwable $e) {
        Response::error('Restore failed: ' . $e->getMessage(), 500);
    }
}

// -----------------------------------------------------------------------------
// 7. Anything else
// -----------------------------------------------------------------------------
header('Allow: GET, POST, PUT');
Response::error('Method not allowed.', 405);
